# Generated by Django 4.2.5 on 2023-09-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ambient_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('ambient_track', models.FileField(help_text='.mp3 supported only', upload_to='ambient_track/')),
            ],
        ),
        migrations.CreateModel(
            name='background_track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('background_track1', models.FileField(help_text='.mp3 supported only', upload_to='background_track/')),
                ('background_track2', models.FileField(help_text='.mp3 supported only', upload_to='background_track/')),
                ('background_track3', models.FileField(help_text='.mp3 supported only', upload_to='background_track/')),
            ],
        ),
    ]
